/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;


public class Order_all extends javax.swing.JFrame {

    /**
     * Creates new form Order_all
     */
    DeliveryService delivery1=new DeliveryService();
    ArrayList<MenuItem>items=new ArrayList<>();
    String roll;
    public Order_all(String rol,DeliveryService delivery) {
        initComponents();
        roll=rol;
        delivery1=delivery;

        //Deserializare(delivery1.table);
        Deserializare(items);
        Deserializare2(items);

        tabel_comanda();
    }

    public Order_all() {
        initComponents();
//Deserializare(delivery1.table);
        tabel_comanda();
    }

    public void Deserializare(ArrayList<MenuItem> ali)
    {
        ArrayList<MenuItem> alimente=new ArrayList<>();
        try{
            FileInputStream fileIn = new FileInputStream("C:\\Users\\HP\\Desktop\\TP teme\\Tema4_tp\\Serializare.ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            MenuItem e;
            while((e=(MenuItem) in.readObject())!=null)
            { alimente.add(e);
            }
            in.close();
            fileIn.close();

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        ali.addAll(alimente);

    }
    public void Deserializare2(ArrayList<MenuItem> ali)
    {
        ArrayList<MenuItem> alimente=new ArrayList<>();
        try{
            FileInputStream fileIn = new FileInputStream("C:\\Users\\HP\\Desktop\\TP teme\\Tema4_tp\\Serializare2.ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            MenuItem e;
            while((e=(MenuItem) in.readObject())!=null)
            { alimente.add(e);
            }
            in.close();
            fileIn.close();

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        ali.addAll(alimente);

    }


    public void tabel_comanda()
    {
        DefaultTableModel df= (DefaultTableModel)jTable1.getModel();
        df.setRowCount(0);
        Object rowData[] = new Object[4];
        for(Map.Entry<Order, ArrayList<MenuItem>>entry:delivery1.table.entrySet())
        {
            Order key= entry.getKey();

            rowData[0] =key.getOrderid();
            rowData[1] = key.getClientid();
            rowData[2] = key.getOrderDate();
            rowData[3] = key.getHour();

            df.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        report1 = new javax.swing.JButton();
        report2 = new javax.swing.JButton();
        report3 = new javax.swing.JButton();
        report4 = new javax.swing.JButton();
        times = new javax.swing.JTextField();
        timef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productnr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ordernr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "OrderId", "ClientId", "Date", "Hour"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        report1.setText("Report1");
        report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report1ActionPerformed(evt);
            }
        });

        report2.setText("Report2");
        report2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report2ActionPerformed(evt);
            }
        });

        report3.setText("Report3");
        report3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report3ActionPerformed(evt);
            }
        });

        report4.setText("Report4");
        report4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report4ActionPerformed(evt);
            }
        });

        jLabel1.setText("start");

        jLabel2.setText("finish");

        productnr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productnrActionPerformed(evt);
            }
        });

        jLabel3.setText("Nr products");

        jLabel4.setText("Nr Orders");

        jLabel5.setText("Price");

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jLabel6.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(113, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(49, 49, 49))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(report4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addContainerGap()))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(report3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(report1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(report2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(productnr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                                                .addComponent(ordernr, javax.swing.GroupLayout.Alignment.LEADING))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(timef, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(28, 28, 28)
                                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(report1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(times, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(timef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)
                                                .addComponent(report4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(report2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(productnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(report3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ordernr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addContainerGap(33, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        this.setVisible(false);
        if(roll.equals("admin")) {
            Admin_view login = new Admin_view(delivery1);
            login.setVisible(true);
        }
        else
        {Login_view l=new Login_view(delivery1);
            l.setVisible(true);}

    }

    private void report1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        int start=Integer.parseInt(times.getText());
        int finish=Integer.parseInt(timef.getText());
        FileWriter Log = null;
        try {
            Log = new FileWriter("Report1.txt", false);
        } catch (IOException e) {
            e.printStackTrace();
        }

Map<Order,ArrayList<MenuItem>>D=(Map<Order, ArrayList<MenuItem>>)delivery1.table;

      Map<Order,ArrayList<MenuItem>> DD=  delivery1.table.entrySet().stream()
                .filter(x->x.getKey().getHour()>=start)
                .filter(x->x.getKey().getHour()<=finish)
                .collect(Collectors.toMap(x->x.getKey(),x->x.getValue()));


for(Map.Entry<Order, ArrayList<MenuItem>>entry:DD.entrySet())
        try {
            Log.write(entry.getKey().toString()+"\n");}
        catch (IOException e) {
            e.printStackTrace();

        }

        try {
            Log.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }


    private void report2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int nr = Integer.parseInt(productnr.getText());
        FileWriter Log = null;
        try {
            Log = new FileWriter("Report2.txt", false);
        } catch (IOException e) {
            e.printStackTrace();
        }
ArrayList<MenuItem> items=new ArrayList<>();
        Deserializare(items);
        Deserializare2(items);
for(MenuItem m:items) {
    int counter=0;
    String s=m.getTitle();
    for(Map.Entry<Order, ArrayList<MenuItem>>entry:delivery1.table.entrySet())
    {
        ArrayList<MenuItem> lista1=entry.getValue();
        for(int i=0;i<lista1.size();i++)
        {
if(s.equals(lista1.get(i).getTitle()))
    counter++;
        }
    }
if(counter>=nr)
    try {
        Log.write(s+"\n");}
    catch (IOException e) {
        e.printStackTrace();

    }

}
        try {
            Log.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }



    private void report3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        FileWriter Log = null;
        try {
            Log = new FileWriter("Report3.txt", false);
        } catch (IOException e) {
            e.printStackTrace();
        }
        int nr=Integer.parseInt(ordernr.getText());
        int prices=Integer.parseInt(price.getText());
        int countnr=0;
        int pricenr=0;
        List<Integer> v= new ArrayList<>();

        for(Map.Entry<Order, ArrayList<MenuItem>> entry : delivery1.table.entrySet()) {
            Order c1 = entry.getKey();
        int ok=0;
            for(int i=0;i<v.size();i++)
        {
            if(c1.getClientid()==v.get(i))
        ok=1;
        }
if(ok==0)
    v.add(c1.getClientid());
        }
        for(int j=0;j<v.size();j++)
        {
            for (Map.Entry<Order, ArrayList<MenuItem>> entry1 : delivery1.table.entrySet()) {
                Order key = entry1.getKey();
                if(v.get(j)==key.getClientid())
                {
                    countnr++;
                    List<MenuItem> s = entry1.getValue();
                int suma=0;
                    for (int i = 0; i < s.size(); i++)
                    {
                        BaseProduct b=(BaseProduct)s.get(i);
                        suma=suma+b.getPrice();
                    }
                pricenr=pricenr+suma;
                }
            }
if(pricenr>=prices && countnr>nr)
    try {
        Log.write( "Clientul"+v.get(j)+ "\n");
    } catch (IOException e) {
        e.printStackTrace();

    }
                }
        try {
            Log.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        }


    private void report4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String data=date.getText();
        FileWriter Log = null;
        try {
            Log = new FileWriter("Report4.txt", false);
        } catch (IOException e) {
            e.printStackTrace();
        }
            ArrayList<MenuItem> ss =new ArrayList<>() ;
        Deserializare(ss);
        Deserializare2(ss);

        Map<Order,ArrayList<MenuItem>> DD=  delivery1.table.entrySet().stream()
                .filter(x->x.getKey().getOrderDate().equals(data))
                .collect(Collectors.toMap(x->x.getKey(),x->x.getValue()));

            for(MenuItem aux:ss)
            {int count=0;
                for (Map.Entry<Order, ArrayList<MenuItem>> entry1 : DD.entrySet())
             {
                 Order key = entry1.getKey();
                 {
                     List<MenuItem> s = entry1.getValue();
                     for (int i = 0; i < s.size(); i++) {
                         if (aux.getTitle().equals(s.get(i).getTitle()))
                             count++;
                     }
                 }
                 }
            if(count!=0)
                try {
                    Log.write( aux.getTitle()+" de "+ count+ "\n");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }


        try {
            Log.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }



    private void productnrActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_all.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_all().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ordernr;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productnr;
    private javax.swing.JButton report1;
    private javax.swing.JButton report2;
    private javax.swing.JButton report3;
    private javax.swing.JButton report4;
    private javax.swing.JTextField timef;
    private javax.swing.JTextField times;
    // End of variables declaration
}
